### PR TITLE
Fix perl Kwalitee issues

### PR DESCRIPTION
**Pull request by waterkip**
This fixes some of the kwalitee issues found on https://cpants.cpanauthors.org/release/RHARMAN/Parse-Snort-0.9

### CODE REVIEW

**Comment by warewolf** [comment]
Aha!  Finally I see this reason as to why you're nuking the MYMETA files:

http://neilb.org/2015/10/18/spotters-guide.html

> MYMETA.yml and MYMETA.json
> 
> These files are similar to the META.* files described above, with a subtle difference:
> 
>     The META.yml and META.json files are generated at release time by the author and included in the tarball that's uploaded to CPAN.
>     The MYMETA.yml and MYMETA.json files are generated at configuration time, ie when the installer runs perl Makefile.PL or perl Build.PL, and should not be included in the tarball.
> 

Next time I goof up (which is bound to happen again) take a moment to point out and explain what the goof was?  That will help me understand.  Thanks for all the help, and PR approved.

**Comment by waterkip** [comment]
Hi, that's why I submitted the link to the kwalitee report. So you would see the reason of the changes. I'm not sure how to deal with the PAX unit, as I don't have a Mac, so that is something you probably need to fix.

I'll make my next commit message more clear in case of these kinda gotcha's :)

Cheers!

**Comment by warewolf** [comment]
Oh, my eyeballs autoincorrected that link into thinking it was just a link to the dist tarball.  Okay, my bad.

**Comment by warewolf** [comment]
PAX headers ... that might be from me using tarballs produced by github?  I'll see if doing a 'make dist' locally has any change on that.

Also - how do you feel about us having a devel branch here for working on, and making master stable, where releases are tagged?  That way I'm not just randomly picking a time "eh, this looks good enough for a release" and it's more coordinated (with stuff you want, etc).

**Comment by waterkip** [comment]
Ahhh, that might explain the errors with the MANIFEST file as well, since github doesn't do a `make dist`. I was playing the various options too see if I could reproduce the errors regarding the MANIFEST files. But I could not reproduce it.

I think setting up travis would be a good start before setting up a master/devel kinda development setup.
For my own projects I work with gitlab and I let gitlab CI do all the testing. As soon as the pipeline works I'm ok with releasing the module. My devel branch is my feature branch. I also use distzilla to release my own modules.

This is my workflow:
Have a `Dockerfile`, have a `.gitlab-ci.yml` file. As soon as the docker build succeeds (which is install all the deps (including their testsuite) and run our own testsuite, the pipeline succeeds and I'm allowed to merge into master. That is the basic idea. And when the master branch also had a successful build I release the module with Distzilla.

At work we use a devel (sprint) branch for this. Our master stays sane. But there we have more iterations and developers per feature and integration with other systems.

I'm not opposed, but I'm also not convinced this project is big enough to have a seperate devel branch.  
Maybe play more with trial releases: VERSION = 0.01_1 etc. I'm not sure how CPAN testers and CPANTS deal with trial releases tho.. 

But you are the project master, so what works best for you.

**Pull request merged**
