### PR TITLE
Only process valid rules

### PR DESCRIPTION
**Pull request by waterkip**
Only process rules which are defined by RULE_ACTIONS. Update POD to
reflect this.

### CODE REVIEW

**Comment by waterkip** [comment]
You said something about only parsing valid rules, so I made something that croaks when rules are not rules (or don't start with something that looks like a rule action).

**Comment by warewolf** [comment]
The way I wanted it was a _subclass_ of the parent module enforced sanity, not the parent module itself.  I wanted Parse::Snort to be semi-future proof; as long as the "format" stayed the same.  Lemme look at your patch though.

**Comment by warewolf** [comment]
Do you mind if I refactor this a bit, into a subclass later today, say around 2300 UTC?

**Comment by waterkip** [comment]
Nope, go ahead :) I will be sleeping at 23:00 UTC (am CEST based).

**Comment by warewolf** [comment]
Yeah, saw Amsterdam in your profile figured you'd understand UTC.  I'm EST5EDT.

**Comment by warewolf** [comment]
Gonna see how well this works this way, over in #5.

**Pull request closed without merging**
